# Generated by Django 5.2.6 on 2025-10-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_bookissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='action',
            field=models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('lost', 'Lost'), ('overdue', 'Overdue')], default='issued', max_length=10),
        ),
    ]
