version: '3.8'  # Make sure version is specified

services:
  db:
    image: postgres:15
    restart: always
    container_name: college_erp_db
    environment:
      POSTGRES_DB: college_erp_db
      POSTGRES_USER: college_erp_user
      POSTGRES_PASSWORD: Ilikecoding@884d
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: college_erp_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
