version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: college_erp_db
    environment:
      POSTGRES_DB: college_erp_db
      POSTGRES_USER: college_erp_user
      POSTGRES_PASSWORD: StrongPasswordHere
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
